services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: reservation_api_test
    ports:
      - "5432:5432"

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/rails 
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/reservation_api_test
      RAILS_ENV: test
      RACK_ENV: test
      RAILS_MAX_THREADS: 5
      REDIS_URL: redis://redis:6379/1
      TOKENIZER_SECRET: 'randomsecret'

volumes:
  postgres_data:
  bundle_cache: